# 测试DataPro文件夹下的Statistic.py

In [1]:
## 通用测试数据
import numpy as np

data1 = np.array([[1, 2, 3, 4, 5], [2, 3, 4, 5, 6], [2, 3, 4, 5, 6]])
data2 = np.array([[2, 3, 1, 5, 7], [3, 1, 4, 6, 3], [8, 3, 4, 1, 2]])
print('data1: ', data1, sep='\n', end='\n\n')
print('data2: ', data2, sep='\n', end='\n\n')
print('data1 - data2: ', data1 - data2, sep='\n')

data1: 
[[1 2 3 4 5]
 [2 3 4 5 6]
 [2 3 4 5 6]]

data2: 
[[2 3 1 5 7]
 [3 1 4 6 3]
 [8 3 4 1 2]]

data1 - data2: 
[[-1 -1  2 -1 -2]
 [-1  2  0 -1  3]
 [-6  0  0  4  4]]


## 测试RMSE()函数

In [2]:
# # 安装MeteoPy之后，正式使用不需要这两句 # #
import sys
sys.path.append('../../')
# # # # # # # # # # # # # # # # # # # # # #
from MeteoPy import RMSE

In [3]:
RMSE(data1, data2, axis=0)

array([3.55902608, 1.29099445, 1.15470054, 2.44948974, 3.10912635])

In [4]:
RMSE(data1, data2, axis=1)

array([1.4832397 , 1.73205081, 3.68781778])

## 测试MAE()函数

In [5]:
# # 安装MeteoPy之后，正式使用不需要这两句 # #
import sys
sys.path.append('../../')
# # # # # # # # # # # # # # # # # # # # # #
from MeteoPy import MAE

In [6]:
MAE(data1, data2, axis=0)

array([2.66666667, 1.        , 0.66666667, 2.        , 3.        ])

In [7]:
MAE(data1, data2, axis=1)

array([1.4, 1.4, 2.8])

## 测试contrast()函数

In [8]:
# # 安装MeteoPy之后，正式使用不需要这两句 # #
import sys
sys.path.append('../../')
# # # # # # # # # # # # # # # # # # # # # #
from MeteoPy import contrast

In [9]:
contrast(data1, data2, axis=0)

MAE      RMSE         R   P-value
0  2.666667  3.559026  0.628619  0.567241
1  1.000000  1.290994      -0.5  0.666667
2  0.666667  1.154701       1.0       0.0
3  2.000000  2.449490 -0.327327  0.787704
4  3.000000  3.109126 -0.981981  0.121038

In [10]:
contrast(data1, data2, axis=1)

MAE      RMSE         R   P-value
0  1.4  1.483240  0.787839  0.113502
1  1.4  1.732051  0.435194  0.463918
2  2.8  3.687818 -0.819288  0.089676